def handle_exception():
    pass